os: linux
language: C++

install:
  - sudo apt install gcc
  - sudo apt-add-repository -y ppa:beineri/opt-qt-5.12.1-xenial
  - travis_wait 30
  - sudo apt-get -qq update
  - sudo apt-get -qq install qt512tools qt512base
  - source /opt/qt512/bin/qt512-env.sh
  - sudo apt-get install -qq qtdeclarative5-dev build-essential

script:
  - qmake -v
  - qmake -r
  - make
  - cd test
  - ./rheda-messenger-tests
