os: linux
language: C++
dist: xenial

install:
  - sudo apt install gcc
  - sudo apt-add-repository -y ppa:beineri/opt-qt-5.14.1-xenial
  - travis_wait 30
  - sudo apt-get -qq update
  - sudo apt-get -qq install qt514tools qt514base
  - source /opt/qt514/bin/qt514-env.sh
  - sudo apt-get install -qq qtdeclarative5-dev build-essential

services:
  - xvfb

before_script:
  - "export DISPLAY=:99.0"

script:
  - qmake -v
  - qmake -r
  - make
  - cd test/test_cpp/
  - ./rheda-test-cpp
  - export QT_QPA_PLATFORM='offscreen'
  - cd ../test_qml/test_message_model/
  - ./test-message-model
  - cd ../test_model_provider/
  - ./test-model-provider
  - cd ../test_user_list_model/
  - ./test-user-list-model
